/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/**
 * The slots a clip can ask for — the declaration alone, nothing that loads.
 *
 * Apart from `dataset.ts` so the browser-side store can name its slots without
 * importing the loader, and the loader can read the store: the two need each
 * other in both directions, and a cycle between them would work today only
 * because every reference sits inside a function body.
 *
 * # Why the files themselves are not in the repository
 * This repository is public, and a clip worth recording plays against a real
 * building rather than a sample. The repository carries the expectation, never
 * the data. A checkout without the files still builds, still type-checks, and
 * tells whoever presses play exactly which file is missing.
 */

const DEMO_LOCAL = '/demo-local';

/**
 * One entry per file a clip may load. The names are deliberately generic and
 * deliberately stable: they are what the viewer's model list shows, and
 * therefore what ends up burned into the finished video.
 *
 * `howToGetDe` is carried here rather than left to whoever reports the gap: a
 * checkout is missing these by design, so "not there" is the normal state, and
 * a message that only names the file leaves the reader to go find out that one
 * of them is generated by a script in this repository and the others are not.
 *
 * `accept` is what the upload picker offers for the slot. Narrow on purpose:
 * dropping an IFC into the drawing slot fails much later, inside a DXF parser.
 */
export const DEMO_FILES = {
  architecture: {
    path: `${DEMO_LOCAL}/demo-architecture.ifc`,
    name: 'demo-architecture.ifc',
    accept: '.ifc',
    howToGetDe: 'aus dem privaten Demodatensatz kopieren oder hier hochladen',
  },
  fireDetection: {
    path: `${DEMO_LOCAL}/demo-fire-detection.ifc`,
    name: 'demo-fire-detection.ifc',
    accept: '.ifc',
    howToGetDe: 'aus dem privaten Demodatensatz kopieren oder hier hochladen',
  },
  /** The drawing traced in strand 1. Generated, so a checkout can make its own;
   *  swap in a real project plan and the clip's coordinates move to match it. */
  plan: {
    path: `${DEMO_LOCAL}/demo-plan.dxf`,
    name: 'demo-plan.dxf',
    accept: '.dxf',
    howToGetDe: 'erzeugen mit `node tools/screenflow/make-demo-plan.mjs` oder hier hochladen',
  },
} as const;

export type DemoFileId = keyof typeof DEMO_FILES;

/** Whether a string names a slot — for reading back untrusted storage keys. */
export function isDemoFileId(value: unknown): value is DemoFileId {
  return typeof value === 'string' && Object.hasOwn(DEMO_FILES, value);
}
